# 1. Create a 3x3x3 array with random values 

In [8]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.78374298 0.27272155 0.59343397]
  [0.0574308  0.03287453 0.22325588]
  [0.11705144 0.86169552 0.29274162]]

 [[0.67222157 0.42648451 0.73944165]
  [0.3507277  0.29543452 0.81896797]
  [0.71656667 0.12741094 0.50160192]]

 [[0.13975683 0.9169521  0.35797569]
  [0.17624956 0.19829483 0.61860777]
  [0.66769517 0.11685296 0.20049261]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
x = np.diag(1+np.arange(4), k = -1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.75440876 0.27746093 0.50236251 0.81241562 0.59438363]
 [0.3336261  0.54383353 0.43972881 0.62805865 0.71565833]
 [0.92708619 0.85543798 0.9385449  0.12123023 0.65887379]
 [0.0250849  0.44422729 0.39151178 0.23070762 0.26295316]
 [0.28944103 0.98278552 0.84559642 0.43128975 0.65101543]]
After normalization:
[[0.76153637 0.26352288 0.49835784 0.82210527 0.59444331]
 [0.32216874 0.54166053 0.43295775 0.62960569 0.72107443]
 [0.94184057 0.86702782 0.95380538 0.10039184 0.66178185]
 [0.         0.43765492 0.3826111  0.21470459 0.24837434]
 [0.27603212 1.         0.85675158 0.42414596 0.65357641]]


# 5.  How to find common values between two arrays?

In [11]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [12]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [13]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 0 0 1 0]
Second array:
[0 0 0 0 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.12391556 0.13459628 0.52631541 0.58856465 0.01546496 0.04792699
 0.28029413 0.42020176 0.68408057 0.2255594 ]
Maximum value replaced by 0:
[0.12391556 0.13459628 0.52631541 0.58856465 0.01546496 0.04792699
 0.28029413 0.42020176 0.         0.2255594 ]


# 9. How to print all the values of an array?

In [38]:
import numpy as np
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [18]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.61051034 0.57762869 0.15597001 0.64918719 0.69245433 0.89566463
  0.44132176 0.79928813 0.40535351 0.45707169]
 [0.98333306 0.90010539 0.29137135 0.59590887 0.26890719 0.46809618
  0.28412748 0.64320813 0.80816354 0.68514841]
 [0.32521615 0.07013386 0.0171136  0.4755819  0.46882676 0.15180111
  0.3186208  0.47914666 0.80332188 0.04278235]
 [0.03598391 0.81084184 0.33103215 0.75650523 0.48069095 0.82578796
  0.67881716 0.44253217 0.60127591 0.72323858]
 [0.31517677 0.83962088 0.57000925 0.53327408 0.25393977 0.93393062
  0.4937238  0.89601949 0.00373727 0.34998644]]

Subtract the mean of each row of the said matrix:

[[ 0.04206531  0.00918366 -0.41247502  0.08074216  0.1240093   0.3272196
  -0.12712327  0.2308431  -0.16309151 -0.11137334]
 [ 0.3904961   0.30726843 -0.30146561  0.00307191 -0.32392977 -0.12474078
  -0.30870948  0.05037117  0.21532658  0.09231145]
 [ 0.00996164 -0.24512065 -0.2981409   0.16032739  0.15357226 -0.1634534
   0.0033663   0.16389215  0.488

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [19]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 4. 2. 5. 3. 3. 2. 5. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [21]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([ 6, 37, 60])

# 13.How to find the most frequent value in an array?

In [26]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[6 7 5 5 9 0 9 6 6 2 5 2 6 0 6 4 4 9 1 5 6 3 6 9 0 3 7 2 2 2 8 5 1 8 2 0 1
 3 2 5 0 5 3 0 2 7 5 2 2 9]
rank: 2


# 14.How to get the n largest values of an array

In [27]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


# 15.How to create a record array from a regular array?

In [35]:
import numpy as np
a1=np.array([1,2,3,4])
#a2=np.array(['Red','Green','White','Orange'])
#a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1,)
(2,)
(3,)
